title: micro:bit selfies
hero_image: images/banner.png
description: Taking selfies with the micro:bit and a Raspberry Pi
original_url: https://raspberrypi.org/learning/microbit-selfies
theme: navy
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 2, design-0, programming-2, phys-comp-2, manufacture-0, community-0
interests: photography
technologies: raspberry-pi, electronic-components, python, microbit
site_areas: projects
hardware: raspberry-pi, electronic-components, microbit
software: python
version: 3
last_tested: 2017-01-01
steps: 
- title: Introduction
- title: What you will need
- title: Connect the camera and micro:bit
- title: Build the micro:bit trigger
- title: Program the micro:bit trigger
- title: Program the Raspberry Pi camera
- title: What next?